sudo: required
services:
  - docker

before_install:
  - docker build -t danielxburns/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielxburns/react-test npm test

after_success:
  - docker build -t danielxburns/multi-client ./client
  - docker build -t danielxburns/multi-nginx ./nginx
  - docker build -t danielxburns/multi-server ./server
  - docker build -t danielxburns/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push danielxburns/multi-client
  - docker push danielxburns/multi-nginx
  - docker push danielxburns/multi-server
  - docker push danielxburns/multi-worker

